handlername = demo;
namespace = galois::user;

find_xdv:
select
    user_table.user_id, user_table.user_stat, user_table.region,
    plan_table.plan_id, plan_table.region,
    unit_table.unit_id, xdv_table.xdv_id
from 
    xdv_table
    join user_table scan limit $scanlimit1 each scan limit $eachscanlimit1 on (xdv_table.user_id  = user_table.user_id)
    leftjoin plan_table scan limit $scanlimit2 each scan limit $eachscanlimit2 on (xdv_table.plan_id  = plan_table.plan_id)
    leftjoin unit_table scan limit $scanlimit3 each scan limit $eachscanlimit3 on (xdv_table.unit_id  = unit_table.unit_id)
where
    xdv_table.xdv_id in $xdv_id_list and
    not (user_table.user_stat = $one)
    and user_table.region in $TargetRegion
    and plan_table.region in $TargetRegion
    or (
        @len(user_table.url_sign) != $zero
        and @max(xdv_table.bid) >= $one
        and @not_null(plan_table.plan_id) = $true
    )
;

find_user:
select 
    user_table.user_id
from 
    user_table
where
    user_table.region = $TargetRegion
;